name: sync_list_view
description: A ListView that allows you to sync tabs with contents
version: 0.0.2
homepage: https://github.com/iisprey/sync_list_view

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.3.4
  scrollable_positioned_list: ^0.2.0-nullsafety.0
